### ISSUE TITLE
fork methond

### ISSUE THREAD

**Issue by fanatid** [AugurProject/augur-abi#7]
How this can be true? `unforked` can be negative?
```js
var superforked = unforked.plus(this.constants.MOD);
if (superforked.gte(this.constants.BYTES_32) && superforked.lt(this.constants.MOD)) {
  unforked = superforked;
}
```

https://github.com/AugurProject/augur-abi/blob/4b228f5c606602bbbac0cef4b65551fc403f7465/index.js#L239

**Comment by tinybike** [comment]
Yes -- basically what this method does is it turns int256's (which can be negative) into uint256's (which can't).  Reason it exists is because most of our contracts work with and return int256 values for hashes we use as IDs (e.g., order IDs).  These hashes are often negative.  However, when these fields are indexed and used as filter topics (in e.g., `eth_getLogs`), they're required to be uint256.

(At one point, we referred to the int256 as "f*cked hex" and uint256 as "unf*cked hex", which is where the name `unfork` comes from...)
